#cloud-config

coreos:
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/99ffe55b47de7e62e686a6cba4c826ef
    # multi-region deployments, multi-cloud deployments, and droplets without
    # private networking need to use $public_ipv4
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  fleet:
    public-ip: $private_ipv4   # used for fleetctl ssh command
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
  users:
    - name: coreos
    
  ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDbg+wDPZO4h0ASEvLo7KfxNicAbvwZQ3VPHHdrd8PZNZyO0cRSOaQv84Jx/ex8Or+qsX6KkVCdGSkRylqmyEd1w/CqtLBSIM2bs1zxUg6ea2K9PKjqWDLykTnVsCACCo6COVZMZ+GdBTvbin+XefQuBkpsEd9A4M5XDsg5qItM4ZIOsHM66dmHbPBFtFUlmLZRYz2hC$KdVbbNzwgd03OcaBPJPmfuiMooLMr0IY/LtIV/mmWc8ilycqxWn/QGt/haMyw9bW/qKjrD92WdnkvWHYusEwQtB8OCo+yatNb3Jzgfm/Htfbwp/aQsROUaJXyI3A7VVLqf7d7I/7AkCkfY3 name@example.org
