#cloud-config

coreos:
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/99ffe55b47de7e62e686a6cba4c826ef
    # multi-region deployments, multi-cloud deployments, and droplets without
    # private networking need to use $public_ipv4
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  fleet:
    public-ip: $private_ipv4   # used for fleetctl ssh command
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
  users:
    - name: coreos
    
  ssh_authorized_keys:
    - ssh-rsa ABCDB3abcdefghijklmnopqrstuvwxyz7890/zabcdefghijklmnopqrstuvwxyzwQPMa5N3Gc0Gum6J17tYbmOemXkgWcrSC+qmeoptjZACabcdefghijklmnopqrstuvwxyzI3J/Mi/swtn1abcdefghijklmnopqrstuvwxyzdefghijklmnopqrstuvwxyzXQjIGW33kHMrXLYLabcdefghijklmnopqrstuvwxyzq0Bvq0tyyVKlabcdefghijklmnopqrstuvwxyzb5X2IjdFIkl8tKl9u8FyoFv+1234567890QKI5QbabcdefghijklmnopqrstuvwxyzHpr0PeIu2GgWUu/2Te0YWRabcdefghijklmnopqrstuvwxyzc/TODInyz5w64dDYDZ1234567890 core@dockcore.com
